"""make report_id nullable

Revision ID: 3ee07eb8a185
Revises: 7f8eba88fae6
Create Date: 2026-09-16 14:14:34.889400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee07eb8a185'
down_revision: Union[str, Sequence[str], None] = '7f8eba88fae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_with_group', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_zone_report_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_zone_report_id', 'report_zones', ['report_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_with_group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_zone_report_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_zone_report_id'), 'report_zones', ['report_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
