"""VehiclleModel nullabale

Revision ID: 3f0cc4c8baac
Revises: cbae411c666a
Create Date: 2026-09-30 14:07:57.929166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0cc4c8baac'
down_revision: Union[str, Sequence[str], None] = 'cbae411c666a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_movements')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_movements',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Номер', sa.VARCHAR(), nullable=False),
    sa.Column('Дата', sa.DATETIME(), nullable=True),
    sa.Column('Заказ', sa.VARCHAR(), nullable=True),
    sa.Column('Точка регистрации', sa.VARCHAR(), nullable=True),
    sa.Column('VehicleModel', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Номер')
    )
    # ### end Alembic commands ###
