"""zone model with child

Revision ID: 7f8eba88fae6
Revises: 
Create Date: 2026-09-10 16:09:45.601172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8eba88fae6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zone_with_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['zone_with_group.id'], name='fk_zone_group_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['report_zones.id'], name='fk_zone_report_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name='uq_zone_name_per_group')
    )
    op.drop_table('zone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('x', sa.FLOAT(), nullable=False),
    sa.Column('y', sa.FLOAT(), nullable=False),
    sa.Column('color', sa.VARCHAR(), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=False),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['zone_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name=op.f('uq_zone_name_per_group'))
    )
    op.drop_table('zone_with_group')
    op.drop_table('report_zones')
    # ### end Alembic commands ###
