"""ZoneWithGroup coordinate nullable set False

Revision ID: bc4f6d15be06
Revises: 7f8eba88fae6
Create Date: 2026-09-15 12:07:42.016828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4f6d15be06'
down_revision: Union[str, Sequence[str], None] = '7f8eba88fae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    op.drop_table('zones_config')
    with op.batch_alter_table('zone_with_group', schema=None) as batch_op:
        batch_op.alter_column('x',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zone_with_group', schema=None) as batch_op:
        batch_op.alter_column('y',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('x',
               existing_type=sa.FLOAT(),
               nullable=False)

    op.create_table('zones_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zones', sa.TEXT(), nullable=False),
    sa.Column('zones_rep', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metadata',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###
