"""VehicleModel

Revision ID: cbae411c666a
Revises: 3ee07eb8a185
Create Date: 2026-09-29 09:53:28.819547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbae411c666a'
down_revision: Union[str, Sequence[str], None] = '3ee07eb8a185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zones_config')
    op.drop_table('metadata')
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VehicleModel', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movements', schema=None) as batch_op:
        batch_op.drop_column('VehicleModel')

    op.create_table('metadata',
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('zones_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zones', sa.TEXT(), nullable=False),
    sa.Column('zones_rep', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
